version: "3.9"

services:
  snippet_manager_service:
    container_name: "snippet_manager_service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SPRING_PORT_SNIPPET_MANAGER}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_SNIPPET_MANAGER}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME_SNIPPET_MANAGER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD_SNIPPET_MANAGER}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO_SNIPPET_MANAGER}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE_SNIPPET_MANAGER}
    depends_on:
      - snippet_manager_db

  snippet_manager_db:
    container_name: snippet_manager_db
    image: postgres:16
    ports:
      - "${POSTGRES_PORT_SNIPPET_MANAGER}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_SNIPPET_MANAGER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_SNIPPET_MANAGER}
      - POSTGRES_DB=${POSTGRES_DB_SNIPPET_MANAGER}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
